/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PropuestaRouteImport } from './routes/propuesta'

const PropuestaRoute = PropuestaRouteImport.update({
  id: '/propuesta',
  path: '/propuesta',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/propuesta': typeof PropuestaRoute
}
export interface FileRoutesByTo {
  '/propuesta': typeof PropuestaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/propuesta': typeof PropuestaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/propuesta'
  fileRoutesByTo: FileRoutesByTo
  to: '/propuesta'
  id: '__root__' | '/propuesta'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PropuestaRoute: typeof PropuestaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/propuesta': {
      id: '/propuesta'
      path: '/propuesta'
      fullPath: '/propuesta'
      preLoaderRoute: typeof PropuestaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  PropuestaRoute: PropuestaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
