/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as EnviosRouteImport } from './routes/envios'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as NosotrosRouteImport } from './routes/nosotros'
import { Route as PropuestaRouteImport } from './routes/propuesta'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TiendaRouteImport } from './routes/tienda'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as TiendaIndexRouteImport } from './routes/tienda.index'
import { Route as TiendaSlugRouteImport } from './routes/tienda.$slug'
import { Route as TiendaCategoriaCategoriaRouteImport } from './routes/tienda.categoria.$categoria'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const EnviosRoute = EnviosRouteImport.update({
  id: '/envios',
  path: '/envios',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const NosotrosRoute = NosotrosRouteImport.update({
  id: '/nosotros',
  path: '/nosotros',
  getParentRoute: () => rootRouteImport,
} as any)
const PropuestaRoute = PropuestaRouteImport.update({
  id: '/propuesta',
  path: '/propuesta',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TiendaRoute = TiendaRouteImport.update({
  id: '/tienda',
  path: '/tienda',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const TiendaIndexRoute = TiendaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TiendaRoute,
} as any)
const TiendaSlugRoute = TiendaSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => TiendaRoute,
} as any)
const TiendaCategoriaCategoriaRoute =
  TiendaCategoriaCategoriaRouteImport.update({
    id: '/categoria/$categoria',
    path: '/categoria/$categoria',
    getParentRoute: () => TiendaRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/blog': typeof BlogRouteWithChildren
  '/contacto': typeof ContactoRoute
  '/envios': typeof EnviosRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/nosotros': typeof NosotrosRoute
  '/propuesta': typeof PropuestaRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tienda': typeof TiendaRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/tienda/$slug': typeof TiendaSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/tienda/': typeof TiendaIndexRoute
  '/tienda/categoria/$categoria': typeof TiendaCategoriaCategoriaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/contacto': typeof ContactoRoute
  '/envios': typeof EnviosRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/nosotros': typeof NosotrosRoute
  '/propuesta': typeof PropuestaRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/tienda/$slug': typeof TiendaSlugRoute
  '/blog': typeof BlogIndexRoute
  '/tienda': typeof TiendaIndexRoute
  '/tienda/categoria/$categoria': typeof TiendaCategoriaCategoriaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/blog': typeof BlogRouteWithChildren
  '/contacto': typeof ContactoRoute
  '/envios': typeof EnviosRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/nosotros': typeof NosotrosRoute
  '/propuesta': typeof PropuestaRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tienda': typeof TiendaRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/tienda/$slug': typeof TiendaSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/tienda/': typeof TiendaIndexRoute
  '/tienda/categoria/$categoria': typeof TiendaCategoriaCategoriaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/blog'
    | '/contacto'
    | '/envios'
    | '/llms.txt'
    | '/nosotros'
    | '/propuesta'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/tienda'
    | '/blog/$slug'
    | '/tienda/$slug'
    | '/blog/'
    | '/tienda/'
    | '/tienda/categoria/$categoria'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$slug'
    | '/contacto'
    | '/envios'
    | '/llms.txt'
    | '/nosotros'
    | '/propuesta'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/blog/$slug'
    | '/tienda/$slug'
    | '/blog'
    | '/tienda'
    | '/tienda/categoria/$categoria'
  id:
    | '__root__'
    | '/'
    | '/$slug'
    | '/blog'
    | '/contacto'
    | '/envios'
    | '/llms.txt'
    | '/nosotros'
    | '/propuesta'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/tienda'
    | '/blog/$slug'
    | '/tienda/$slug'
    | '/blog/'
    | '/tienda/'
    | '/tienda/categoria/$categoria'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SlugRoute: typeof SlugRoute
  BlogRoute: typeof BlogRouteWithChildren
  ContactoRoute: typeof ContactoRoute
  EnviosRoute: typeof EnviosRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  NosotrosRoute: typeof NosotrosRoute
  PropuestaRoute: typeof PropuestaRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TiendaRoute: typeof TiendaRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/envios': {
      id: '/envios'
      path: '/envios'
      fullPath: '/envios'
      preLoaderRoute: typeof EnviosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nosotros': {
      id: '/nosotros'
      path: '/nosotros'
      fullPath: '/nosotros'
      preLoaderRoute: typeof NosotrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/propuesta': {
      id: '/propuesta'
      path: '/propuesta'
      fullPath: '/propuesta'
      preLoaderRoute: typeof PropuestaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tienda': {
      id: '/tienda'
      path: '/tienda'
      fullPath: '/tienda'
      preLoaderRoute: typeof TiendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/tienda/': {
      id: '/tienda/'
      path: '/'
      fullPath: '/tienda/'
      preLoaderRoute: typeof TiendaIndexRouteImport
      parentRoute: typeof TiendaRoute
    }
    '/tienda/$slug': {
      id: '/tienda/$slug'
      path: '/$slug'
      fullPath: '/tienda/$slug'
      preLoaderRoute: typeof TiendaSlugRouteImport
      parentRoute: typeof TiendaRoute
    }
    '/tienda/categoria/$categoria': {
      id: '/tienda/categoria/$categoria'
      path: '/categoria/$categoria'
      fullPath: '/tienda/categoria/$categoria'
      preLoaderRoute: typeof TiendaCategoriaCategoriaRouteImport
      parentRoute: typeof TiendaRoute
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface TiendaRouteChildren {
  TiendaSlugRoute: typeof TiendaSlugRoute
  TiendaIndexRoute: typeof TiendaIndexRoute
  TiendaCategoriaCategoriaRoute: typeof TiendaCategoriaCategoriaRoute
}

const TiendaRouteChildren: TiendaRouteChildren = {
  TiendaSlugRoute: TiendaSlugRoute,
  TiendaIndexRoute: TiendaIndexRoute,
  TiendaCategoriaCategoriaRoute: TiendaCategoriaCategoriaRoute,
}

const TiendaRouteWithChildren =
  TiendaRoute._addFileChildren(TiendaRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlugRoute: SlugRoute,
  BlogRoute: BlogRouteWithChildren,
  ContactoRoute: ContactoRoute,
  EnviosRoute: EnviosRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  NosotrosRoute: NosotrosRoute,
  PropuestaRoute: PropuestaRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TiendaRoute: TiendaRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
